project:
  type: website
  render:
    - "*.qmd"
    - "!*.ipynb"

execute:
  freeze: true

navbar: false

website:
  title: "presentations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
